# Dockerfile for testing only.
#
# There is no point to publishing an actual docker image, since this is a
# library.

FROM golang:alpine

WORKDIR /app

RUN apk --no-cache add build-base opus-dev opusfile-dev

ADD . /app

RUN go test -race ./...
RUN go test -tags nolibopusfile -race ./...
