on: [push, pull_request]
name: Test
jobs:
  full:
    strategy:
      matrix:
        go-version:
          - 1.14.x
        platform:
          # Would like to test mac & win but not sure how to install opus on
          # those in GH actions, yet.
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install system dependencies
      run: sudo apt-get install pkg-config libopus-dev libopusfile-dev moreutils
    - name: Checkout code
      uses: actions/checkout@v2
    # Could be a separate step but this is so quick--just put it here
    - name: Lint
      run: gofmt -d . | tee /dev/stderr | ifne false
    - name: Test
      run: go test -race -v ./...

  no-libopusfile:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Install system dependencies
      run: sudo apt-get install pkg-config libopus-dev
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -tags nolibopusfile -race -v ./...