on: [push, pull_request]
name: Test
jobs:
  native:
    strategy:
      matrix:
        go-version:
          - 1.24.x
          - 1.26.x
        platform:
          # Would like to test mac & win but not sure how to install opus on
          # those in GH actions, yet.
          - ubuntu-latest
          - ubuntu-26.04-arm
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install system dependencies
      run: sudo apt-get install pkg-config libopus-dev libopusfile-dev moreutils
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Test
      run: go test -race -v ./...

  no-libopusfile:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.24.x
    - name: Install system dependencies
      run: sudo apt-get install pkg-config libopus-dev
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Test
      run: go test -tags nolibopusfile -race -v ./...

  docker:
    strategy:
      matrix:
        dist:
          - debian
          - alpine
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: docker build --progress=plain -t latest -f Dockerfile.${{ matrix.dist }} .

  nix:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: ubuntu-26.04-arm
    steps:
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - uses: actions/checkout@v6
    - run: nix-build
    - run: nix flake check -L

  nocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: "nocommit checker"
        uses: nobssoftware/nocommit@v3
